name: GitHub Pages Deploy

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 14
      - run: npm ci
      - run: npm run build:demo
      - run: git remote set-url origin https://git:${GITHUB_TOKEN}@github.com/jacob-lcs/ace-list.git
      - run: npm run deploy -- -u "jacob <jacob.lcs@qq.com>"
        env:
          GITHUB_TOKEN: ${{ secrets.ACCESS_GITHUB_TOKEN }}
